### ISSUE TITLE
Failed to start the minecraft server

### ISSUE THREAD

**Issue by ZettaBytte** [Scouter456/Silents_Delight#5]
Hi, I was just starting a server with a bunch of mods including Silent's Delight, the server didn't started and the log says it has to do with this mod. [Here is the log](https://mclo.gs/ML1iLw5), I'm using the latest version uploaded to fabric and [this version of Farmer's Delight Refabricated](https://modrinth.com/mod/farmers-delight-refabricated/version/1.20.1-2.1.2). The fabric loader version is 0.16.0. Anything you need to help diagnose the problem let me know, thanks in advance!

**Comment by Scouter456** [comment]
Looking at your silents delight version it seems you used the old fabric version, the one that isnt for the refabricated version of farmers delight. Try changing that and try it again.
https://legacy.curseforge.com/minecraft/mc-mods/silents-delight/files/5574405

**Comment by ZettaBytte** [comment]
I changed the version of Farmer's Delight. Instead of refabricated, I'm using the "original", now the log is this one https://mclo.gs/OtSG9g2

**Comment by Scouter456** [comment]
Okay the latest version 1.0.3 should have it fixed

**Comment by ZettaBytte** [comment]
It seems to work perfectly, thank you very much!
